typography_spectrum: 0.6246162924332784
color:
  brandStrength: 0.26918764113402455
  lightness: 0.731990642172681
  saturation: 0.739735364443853
  rhythmicContrast: 0.20369601995490566
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
github: true
layout_spectrum: 0.23597640855634347
author:
  name: Antonio Jacob Martinez
  email: antoniojacobmartinez@gmail.com
  url: 'http://antoniojacobmartinez.com'
name: Antonio Jacob Martinez
navigation:
  - name: About Me
    id: 04268a7c-39d8-4b6f-ba55-7585a7970e33
    type: content
  - name: Anonymous Fathers and Mothers
    id: 30be4b77-5047-4d41-8755-0f5d45cfc571
    type: content
  - name: How to Hug and Other Sublimations of Men
    id: fa14be47-fc5d-4eec-af55-8fa5f1cebac8
    type: content
  - name: Holy X and the 9th
    id: 17afbfbe-8c37-4206-964d-eb6531481d21
    type: content
  - name: 'iPhone '
    id: 1a12e609-8822-4102-9547-0e29f9f2d109
    type: content
  - name: 'Instagram: Antonio Jacob Martinez'
    url: 'https://www.instagram.com/antoniojacobmartinez/'
    type: external
  - name: Archive of Activity
    id: 9d5f6640-89dd-445a-b6cc-a378082b539d
    type: content
  - name: In the News
    id: 76b909c6-432e-49af-80b6-c7c5e32a1e6b
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/828b07fb-a8f9-4bc8-99aa-114ce6c745fd.jpg
title: Antonio Jacob Martinez
content: []
description: Fine Art Photographer
purpose:
  - type: contact
    url: 'mailto:antoniojacobmartinez@gmail.com'
    label: e-mail me.
  - type: internal
    label: About me.
    item: 04268a7c-39d8-4b6f-ba55-7585a7970e33
